name = "Holapack"
author = "Sasha Koshka"
version = "2.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "31e8e43f662999fb6d3e90d659c17b836f3fcae41dbca938a1ac5e37a4a6f1dc"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
