name = "Holapack"
author = "Sasha Koshka"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "66099462ced760f63228c200e775b6aaa7325d921af234ec0ff4775f3445fd0a"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"
