name = "Holapack"
author = "Sasha Koshka"
version = "1.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b7d33b7a7f39b85a90def42ddb761ff98a7a0c5f53b71746db702a46752f9162"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"
