name = "Holapack"
author = "Sasha Koshka"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d63df50362c6de1e52dae88044a0b9cee59d4c804d9a5637a0ae5cea2f34f615"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"
