name = "Holapack"
author = "Sasha Koshka"
version = "2.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0f8609c39f1710661ce3b60910c39cffe8fe926b1376193bfcad8b7e7fe123e2"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
