name = "Holapack"
author = "Sasha Koshka"
version = "1.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7fd7476ce0e387956b01d2934bcbf094346227e72054fbe37de8bcea1cb911ac"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"
