name = "Holapack"
author = "Sasha Koshka"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2fbeeffac318c4df4531daf77b0f0c0f1d2bfa2c0453a8992675ccd256fe0178"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
