name = "Holapack"
author = "Sasha Koshka"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d0b5891344caf9094a2b6d355ffb0da148d3113ae1063b95adb1c993a2a72be6"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
