name = "Holapack"
author = "Sasha Koshka"
version = "2.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e900dd62f93b5ea1b69be94d2a9c528922c6d77251f5291c9ceb7ef48a60cf57"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
