name = "Holapack"
author = "Sasha Koshka"
version = "1.7.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "13855d345f72c75b250f5c8682343fa9767ef3597a9bf4207532ac6d26496677"

[versions]
fabric = "0.14.22"
minecraft = "1.19.2"
