name = "Holapack"
author = "Sasha Koshka"
version = "1.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "74389ed771f8544675ef4a1cd91dafc68796d077dfc5f2f1ce9d5ec67e98b85a"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"
