name = "Holapack"
author = "Sasha Koshka"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "80e3ea9faeb3940bd3b7f40916647f868733c55dc4be191265bfa05ee02f6f75"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"
