name = "Holapack"
author = "Sasha Koshka"
version = "1.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fd7bd385f7c729cc84bc10b51f1f9dd3ed54c19dc54a3d48050e47309b61f76c"

[versions]
fabric = "0.14.22"
minecraft = "1.19.2"
